name: 'Deploy docs'

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 'Deploy docs with npm run deploy'
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: docs-cache-${{ hashFiles('website/package-lock.json') }}
          path: |
            ~/.npm
            .docusaurus

      - name: Install packages
        run: npm ci

      - name: Deploy docs to terser/terser.github.io
        run: npm run deploy