name: 'Deploy docs'

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 'Deploy docs with npm run deploy'
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: docs-cache-${{ hashFiles('website/package-lock.json') }}
          path: |
            ~/.cache/npm
            .docusaurus

      - name: Install packages
        run: npm ci

      - name: Build the docs
        run: npm run build

      - name: Deploy docs to terser/terser.github.io
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          publish_dir: ./build
          external_repository: terser/terser.github.io
          publish_branch: master
          deploy_key: ${{ secrets.TERSER_ORG_DEPLOY_KEY }}